# Generated by Django 5.0.6 on 2026-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
    ]
