# Generated by Django 5.0.6 on 2026-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.TextField(blank=True, default='', help_text='Admin javobi'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_created_at',
            field=models.DateTimeField(blank=True, help_text='Javob berilgan vaqt', null=True),
        ),
    ]
